HW13.1_B09280065/prjFileUpload/prjFileUpload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;

namespace prjFileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: Home
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase photo)
        {
            //上傳圖檔名稱
            string fileName = "";
            //檔案上傳
            if (photo != null)
            {
                if (photo.ContentLength > 0)
                {
                    //取得圖檔名稱
                    fileName = Path.GetFileName(photo.FileName);
                    var path = Path.Combine
                      (Server.MapPath("~/Photos"), fileName);
                    photo.SaveAs(path);
                }
            }
            return RedirectToAction("ShowPhotos");
        }

        // ShowPhotos方法使用ContentResult傳回HTML
        // 可顯示Photos資料夾下所有圖檔
        public ContentResult ShowPhotos()
        {
            string strHtml = "";
            // 建立可操作Photos資料夾的dir物件
            DirectoryInfo dir =
                new DirectoryInfo(Server.MapPath("~/Photos"));
            //取得dir物件下的所有檔案(即photos資料夾下)並放入finfo檔案資訊陣列
            FileInfo[] fInfo = dir.GetFiles();
            // 逐一將finfo檔案資訊陣列內的所有圖檔指定給strHtml變數
            foreach (FileInfo result in fInfo)
            {
                // 將顯示圖的HTML字串指定給strHtml
                strHtml += $"<a href='../Photos/{result.Name}' target='_blank'>" +
                    $"<img src='../Photos/{result.Name}' width='150' height='120' border='0'>" +
                    $"</a>　";
            }
            // strHtml變數再加上 '返回' Create動作方法的連結
            strHtml += "<p><a href='Create'>返回</a></p>";
            return Content(strHtml, "text/html", System.Text.Encoding.UTF8);
        }
    }
}

HW13.1_B09280065/prjFileUpload/prjFileUpload/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjFileUpload.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

HW13.1_B09280065/prjFileUpload/prjFileUpload/Controllers/MultiFileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;

namespace prjFileUpload.Controllers
{
    public class MultiFileUploadController : Controller
    {
        // GET: MultiFileUpload
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase[] photos)
        {
            string fileName = "";
            // 使用for 迴圈取得所有上傳的檔案
            for (int i = 0; i < photos.Length; i++)
            {
                // 取得目前檔案上傳的HttpPostedFileBase物件
                // 即虛引數的photos[i]可以取得第i 個所上傳的檔案
                HttpPostedFileBase f = (HttpPostedFileBase)photos[i];
                // 若目前檔案上傳的HttpPostedFileBase物件的檔案名稱為不為空白
                // 即表示第 i 個f物件有指定上傳檔案
                if (f != null)
                {
                    //取得圖檔名稱
                    fileName = Path.GetFileName(f.FileName);
                    //將檔案儲存到網站的Photos資料夾下
                    var path = Path.Combine
                      (Server.MapPath("~/Photos"), fileName);
                    f.SaveAs(path);
                }
            }
            return RedirectToAction("ShowPhotos");
        }

        // ShowPhotos方法使用ContentResult傳回HTML
        // 可顯示Photos資料夾下所有圖檔
        public ContentResult ShowPhotos()
        {
            string strHtml = "";
            // 建立可操作Photos資料夾的dir物件
            DirectoryInfo dir =
                new DirectoryInfo(Server.MapPath("~/Photos"));
            //取得dir物件下的所有檔案(即photos資料夾下)並放入finfo檔案資訊陣列
            FileInfo[] fInfo = dir.GetFiles();
            // 逐一將finfo檔案資訊陣列內的所有圖檔指定給strHtml變數
            foreach (FileInfo result in fInfo)
            {
                // 將顯示圖的HTML字串指定給strHtml
                strHtml += $"<a href='../Photos/{result.Name}' target='_blank'>" +
                    $"<img src='../Photos/{result.Name}' width='150' height='120' border='0'>" +
                    $"</a>　";
            }
            // strHtml變數再加上 '返回' Create動作方法的連結
            strHtml += "<p><a href='Create'>返回</a></p>";
            return Content(strHtml, "text/html", System.Text.Encoding.UTF8);
        }
    }
}

HW13.1_B09280065/prjFileUpload/prjFileUpload/Views/FileUpload/Create.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>檔案上傳</title>
</head>
<body>
    <form method="post" action="@Url.Action("Create")"
          enctype="multipart/form-data">
        <div>
            請選擇要上傳的檔案
            <input type="file" name="photo" />
            <input type="submit" value="檔案上傳" />
        </div>
    </form>
</body>
</html>

HW13.1_B09280065/prjFileUpload/prjFileUpload/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @Html.ActionLink("1.B09280065 葉家浩 呼叫 FileUploadController", "Create", "FileUpload")
    <br />
    @Html.ActionLink("2.B09280065 葉家浩 呼叫 MultiFileUploadController", "Create", "MultiFileUpload")
</body>
</html>

HW13.1_B09280065/prjFileUpload/prjFileUpload/Views/MultiFileUpload/Create.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>多檔案上傳</title>
</head>
<body>
    <form method="post" action="@Url.Action("Create")"
          enctype="multipart/form-data">
        <div>
            <p>
                上傳檔案 1：<input type="file" name="photos"  />
            </p>
            <p>
                上傳檔案 2：<input type="file" name="photos" />
            </p>
            <p>
                上傳檔案 3：<input type="file" name="photos" />
            </p>
            <input type="submit" value="檔案上傳" />
        </div>
    </form>
</body>
</html>